services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ".data/nodered:/data"